# Base Image
FROM alpine:3.15 AS base

# Copy Over Build Scripts
COPY src /src

# Set Working Directory
WORKDIR /src

# Run Command
RUN apk -U upgrade --no-cache \
    && apk add --no-cache g++ \
    && ./build-project \
    && cp dist/pcg-bunnies /sbin/pcg-bunnies \
    && rm -rf /var/cache/apk/*

# Final Layer
FROM alpine:3.15 AS final

# Copy from Base Layer
COPY --from=base /sbin/pcg-bunnies /sbin/pcg-bunnies

# Init Entry Point
ENTRYPOINT [ "/sbin/init" ]
