site_name: PCG Bunnies
site_description: The Search-Based Approach to Procedural Content Generation
site_author: Matt Buske
copyright: Matt Buske - 2014-2023
repo_url: https://github.com/mattbuske/pcg-bunny
extra:
    version: 1.2.0
plugins:
  - search
  - macros
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
    name: material
    icon:
      logo: material/rabbit-variant
    features:
        - navigation.instant
        - navigation.tracking
        # - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.indexes
        - navigation.top
        - content.code.copy
        - content.tabs
        - content.tabs.link
        - content.code.copy
        - search.suggest
        - search.highlight
        - search.share
    palette:
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue 
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue 
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
'nav':
    - 'Home': 'index.md'
    - 'PCG Bunnies!':
        - 'core/index.md'
        - 'Overview': 'core/overview.md'
        - 'Deep Dive': 'core/deep-dive.md'
        - 'Build': 
              - 'build/index.md'
              - 'C++': 'build/cplusplus.md'
              - 'C#': 'build/csharp.md'
    - 'About':
        - 'Contributing': 'about/contributing.md'
        - 'Code of Conduct': 'about/code-of-conduct.md'
        - 'License': 'about/license.md'
        - 'Release Notes': 'about/release-notes.md'
        - 'Roadmap': 'about/roadmap.md'
